# .github/workflows/deploy-ec2.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/freeswitch
          IMAGE_TAG=${{ github.sha }}
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest ./docker/base_image
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/freeswitch
            IMAGE_TAG=${{ github.sha }}

            echo "Logging in to GHCR..."
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Stopping old container..."
            docker stop freeswitch || true
            docker rm freeswitch || true

            echo "Pulling latest image..."
            docker pull $IMAGE_NAME:$IMAGE_TAG

            echo "Starting new container..."
            docker run -d --name freeswitch -p 5060:5060 -p 5080:5080 $IMAGE_NAME:$IMAGE_TAG
